# site settings
title: William Donovan
subtitle: Personal Website
email: wddonovan@ucdavis.edu
description: Electrical engineer looking for full time positions
# baseurl: "/williamdonovan" # the subpath of your site, e.g. /blog
# url: # the base hostname & protocol for your site
author: William Donovan
street_address: 5722 Raters Drive
city: Santa Rosa
state: CA
zip_code: 95409
country: United States of America
phone: (707) 539-2088

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/wddonovan
gitlab_url:
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/wddonovan/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
